### ISSUE TITLE
Use ROGUE on a large data of single cell

### ISSUE THREAD

**Issue by Zhaohui-Ruan** [PaulingLiu/ROGUE#4]
尊敬的刘博士您好，
我想用您创建的ROGUE，但我的单细胞数据很大（大于2万个基因*大于80w个细胞），我不知道ROGUE是否能够运用于这样大的数据，并有其他几个问题想咨询您。

1. 请问从算法和数学的角度来看，ROGUE能够使用在这样大的数据上嘛？

2. 同时，在以往使用者的问题中，您提到使用ROGUE的时候可能需要调高span，请问这个指调高的程度有什么范围要求或者有什么规律吗？

3. 如果当数据很大的时候，我能对每个cluster进行抽样取一小群来进行计算吗？

谢谢您的帮助，祝好
阮昭慧

**Comment by PaulingLiu** [comment]
谢谢使用ROGUE

1. ROGUE的计算不复杂, 不会消耗很大的内存, 所以如果你的服务器内存足够大,是可以的.

2. span主要是控制拟合的效果,是loess函数里面的一个参数, 你可以用一个简单的数据集测试一下使用不同的span值对应的拟合的图, 就可以挑出你觉得适合的参数啦

3. 是可以抽样来计算的, 只要抽取的细胞数不是太少就可以

希望对你还有帮助
再次感谢使用ROGUE
