### ISSUE TITLE
what's the NA mean in the rouge result

### ISSUE THREAD

**Issue by XinmiaoYan** [PaulingLiu/ROGUE#6]
thanks for building so nice tools.
I got a problem about the result interpretation. I know  a ROGUE value of 1, indicating it is a completely pure subtype or state. In contrast, a population with maximum summarization of significant ds will yield a purity score of ~0. 
but There're several NA in the result, how do we interpret the NA value?

appreciate your response.

**Comment by PaulingLiu** [comment]
Hi @xinmiaoyan ,

Thanks for using this tool. The ROGUE will return a "NA" if a cluster from a given sample contains <10 cells (by default). In such cases, we feel that the purity assessment may not be accurate, and would filter out such NA values.

Please let me know if this is helpful.

**Comment by XinmiaoYan** [comment]
Hi PaulingLiu/ROGUE,
Thanks for your response, it helps a lot.
Have a great day!

Best,
Xinmiao Yan
